---
title: "accuracy_vizualization"
output: html_document
date: "2023-05-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load in packages
```{r}
library(tidyverse)
```
# Load in data
```{r}
accuracies <- read_csv("../data/accuracies.csv")
```
# Draw density plot
```{r}
densities_plot <- ggplot() +
  
  #model performance density curve 
  geom_density(aes(x = accuracies$accuracy, fill = "Accuracy of Model"), color = "white", alpha = 0.95) +
  
  #dummy performance density curve
  geom_density(aes(x = accuracies$`dummy accuracy`, fill ="Accuracy of Always Predicting\nSuccesfull Replication"), color = "white", alpha = 0.65) + 
  
  #manually set color scale
  scale_colour_manual(values = c("coral", "cornflowerblue"), aesthetics = c("colour", "fill")) +
  
  #change label on x-axis
  xlab("Accuracy Scores") +
  
<<<<<<< Updated upstream
=======
  #Change label on y-axis
  ylab("Scaled density") +
  

  xlim(0.3, 0.9) +
  
>>>>>>> Stashed changes
  #use classic theme for axis and background
  theme_classic()  +

  #move legend to inside top left of plot
  theme(legend.position = c(.01, .999), legend.justification = c("left", "top")) +
  
  #remove title from legend
  guides(fill=guide_legend(title=NULL)) 

densities_plot

ggsave("Accuracy_dists.png")

```

